name: 机器人实时状态
module_name: bot_status_now
description: 返回机器人所在服务器的状态
usage: '**[戳一戳机器人]'
status: true
show: true
priority: 1
matchers:
- pm_name: 机器人实时状态
  pm_description: 返回机器人所在服务器的状态
  pm_usage: '**[戳一戳机器人]'
  pm_priority: 1
  pm_show: true
