name: 原神原版模拟抽卡
module_name: Paimon_Gacha
description: 万象、原神的模拟抽卡
usage: ？？？
status: true
show: true
priority: 2
matchers:
- pm_name: 模拟抽卡
  pm_description: 会被记录，且概率仿真的原神模拟抽卡，卡池有常驻|角色1|角色2|武器
  pm_usage: 抽[数量]十连[卡池]
  pm_priority: 1
  pm_show: true
- pm_name: 模拟抽卡记录
  pm_description: 查看模拟抽卡记录
  pm_usage: 模拟抽卡记录[角色|武器]
  pm_priority: 2
  pm_show: true