name: 原神语音
module_name: Genshin_Voice
description: 原神语音
usage: 原神猜语音
status: true
show: true
priority: 6
matchers:
- pm_name: 原神猜语音
  pm_description: 原神猜语音小游戏
  pm_usage: 原神猜语音[语言][排行榜]
  pm_priority: 1
  pm_show: true
- pm_name: 原神语音列表
  pm_description: 查看角色的语音列表
  pm_usage: 原神语音列表<名><语言>
  pm_priority: 2
  pm_show: true
- pm_name: 原神语音
  pm_description: 获取指定角色的指定语音
  pm_usage: 原神语音<名|序号>[语言]
  pm_priority: 3
  pm_show: true
- pm_name: 更新原神语音资源
  pm_description: 更新原神语音资源
  pm_usage: 更新原神语音资源
  pm_priority: 4
  pm_show: false
