name: 米游币商品自动兑换插件
module_name: nonebot_plugin_myb_exchange
description: 录入米游币兑换计划，Bot会在对应时间自动帮你抢兑商品
usage: "myb 跟随Bot的指引录入兑换计划\nmyb_info 查看当前的兑换计划\nmyb_delete 删除你的所有兑换计划\n"
status: true
show: true
priority: 99
matchers:
- pm_name: 米游币兑换
  pm_description: 录入米游币商品自动兑换计划
  pm_usage: myb
  pm_priority: 15
  pm_show: true
- pm_name: 米游币兑换信息
  pm_description: 查看你的米游币兑换计划
  pm_usage: myb_info
  pm_priority: 16
  pm_show: true
- pm_name: 米游币兑换删除
  pm_description: 取消你的米游币兑换计划
  pm_usage: myb_delete
  pm_priority: 17
  pm_show: true
