name: 原神Wiki
module_name: Paimon_Wiki
description: 原神WIKI百科
usage: "\"1.[xx角色攻略]查看西风驿站出品的角色一图流攻略\n\"\n\"2.[xx角色材料]查看惜月出品的角色材料统计\n\"\n\"3.[xx参考面板]查看blue菌hehe出品的参考面板攻略\n\
  \"\n\"4.[xx收益曲线]查看blue菌hehe出品的收益曲线攻略\n\"\n\"5.[今日/明日/周x材料]查看每日角色天赋材料和武器突破材料表\n\"\
  \n\"6.[xx武器攻略]查看武器攻略\n\"\n\"7.[xx原魔图鉴]查看原魔图鉴\n\"\n"
status: true
show: true
priority: 3
matchers:
- pm_name: 角色攻略
  pm_description: 查看该角色的角色攻略
  pm_usage: <角色名> 角色攻略
  pm_priority: 5
  pm_show: true
- pm_name: 圣遗物图鉴
  pm_description: 查看该圣遗物的圣遗物图鉴
  pm_usage: <圣遗物名> 圣遗物图鉴
  pm_priority: 5
  pm_show: true
- pm_name: 参考面板
  pm_description: 查看该角色的参考面板
  pm_usage: <角色名> 参考面板
  pm_priority: 5
  pm_show: true
- pm_name: 武器图鉴
  pm_description: 查看该武器的武器图鉴
  pm_usage: <武器名> 武器图鉴
  pm_priority: 5
  pm_show: true
- pm_name: 角色材料
  pm_description: 查看该角色的角色材料
  pm_usage: <角色名> 角色材料
  pm_priority: 5
  pm_show: true
- pm_name: 原魔图鉴
  pm_description: 查看该原魔的原魔图鉴
  pm_usage: <原魔名> 原魔图鉴
  pm_priority: 5
  pm_show: true
- pm_name: 收益曲线
  pm_description: 查看该角色的收益曲线
  pm_usage: <角色名> 收益曲线
  pm_priority: 5
  pm_show: true
- pm_name: 每日材料
  pm_description: 查看某日开放材料刷取的角色和武器
  pm_usage: <今天|周几>材料
  pm_priority: 8
  pm_show: true
