name: 求签【谜语人版】
module_name: sign_new
description: 向境神求签，获得一张引子
usage: 求签
status: true
show: true
priority: 2
matchers:
- pm_name: 求签
  pm_description: 向境神求签，获得一张引子
  pm_usage: 求签
  pm_priority: 2
  pm_show: true
