群聊学习总开关: true
屏蔽词: []
屏蔽群: []
屏蔽用户: []
单句关键词分词数量: 3
发言阈值: 4
发言阈值权重:
- 10
- 30
- 60
跨群回复阈值: 2
复读阈值: 3
主动发言阈值: 5
按逗号分割回复概率: 0.5
以语音回复概率: 0.1
连续主动发言概率: 0.5
主动发言附带戳一戳概率: 0.5
最大连续说话句数: 3
持久化间隔秒数: 3600
持久化间隔条数: 1000
