启用CookieWeb: true
CookieWeb地址: http://127.0.0.1:13579/LittlePaimon/cookie
模拟抽卡群冷却: 30
模拟抽卡群员冷却: 60
模拟抽卡单次最多十连数: 5
米游币自动获取开关: true
米游币开始执行时间(小时): 8
米游币开始执行时间(分钟): 0
米游社自动签到开关: true
米游社签到开始时间(小时): 0
米游社签到开始时间(分钟): 5
实时便签检查开关: true
实时便签停止检查开始时间: 0
实时便签停止检查结束时间: 6
实时便签检查间隔: 16
原神语音合成冷却: 10
ys自动更新小时: 24
ysa自动更新小时: 24
ysd自动更新小时: 6
云原神自动签到开关: true
云原神签到时间(小时): 7
启用好友和群请求通知: true
自动接受好友请求: false
自动接受群邀请: false
启用好友和群欢迎消息: true
